/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "sipo.v:1.1-15.10" *)
module sipo(clk, rst_n, data, q);
  (* src = "sipo.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "sipo.v:4.23-4.27" *)
  input data;
  wire data;
  (* src = "sipo.v:5.23-5.24" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "sipo.v:4.16-4.21" *)
  input rst_n;
  wire rst_n;
  (* src = "sipo.v:7.5-14.8" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(q[1]),
    .Q(q[0]),
    .RESET_B(rst_n)
  );
  (* src = "sipo.v:7.5-14.8" *)
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(q[2]),
    .Q(q[1]),
    .RESET_B(rst_n)
  );
  (* src = "sipo.v:7.5-14.8" *)
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(q[3]),
    .Q(q[2]),
    .RESET_B(rst_n)
  );
  (* src = "sipo.v:7.5-14.8" *)
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(data),
    .Q(q[3]),
    .RESET_B(rst_n)
  );
endmodule
