/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "d_ff_async.v:1.1-14.10" *)
module d_ff_async(clk, rst_n, d, q);
  (* src = "d_ff_async.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "d_ff_async.v:3.11-3.12" *)
  input d;
  wire d;
  (* src = "d_ff_async.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "d_ff_async.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  (* src = "d_ff_async.v:6.5-13.8" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RESET_B(rst_n)
  );
endmodule
