/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "async_counter.v:1.1-17.10" *)
module counter(clk, rst_n, counter);
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "async_counter.v:14.24-14.37|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "async_counter.v:14.24-14.37|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  (* src = "async_counter.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "async_counter.v:6.27-6.34" *)
  output [3:0] counter;
  wire [3:0] counter;
  (* src = "async_counter.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(counter[0]),
    .Y(_02_[0])
  );
  sky130_fd_sc_hd__xor2_1 _05_ (
    .A(counter[0]),
    .B(counter[1]),
    .X(_03_[1])
  );
  sky130_fd_sc_hd__nand3_1 _06_ (
    .A(counter[0]),
    .B(counter[1]),
    .C(counter[2]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _07_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(counter[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _08_ (
    .A(_00_),
    .SLEEP(_01_),
    .X(_03_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(counter[3]),
    .B(_00_),
    .Y(_03_[3])
  );
  (* src = "async_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(counter[0]),
    .RESET_B(rst_n)
  );
  (* src = "async_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_03_[1]),
    .Q(counter[1]),
    .RESET_B(rst_n)
  );
  (* src = "async_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(_03_[2]),
    .Q(counter[2]),
    .RESET_B(rst_n)
  );
  (* src = "async_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(_03_[3]),
    .Q(counter[3]),
    .RESET_B(rst_n)
  );
  assign _02_[3:1] = counter[3:1];
  assign _03_[0] = _02_[0];
endmodule
