/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "mealy_fsm.v:1.1-53.10" *)
module mealy(clk, rst_n, in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "mealy_fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "mealy_fsm.v:2.21-2.23" *)
  input in;
  wire in;
  (* src = "mealy_fsm.v:11.20-11.24" *)
  wire [2:0] n_st;
  (* src = "mealy_fsm.v:3.16-3.19" *)
  output out;
  wire out;
  (* src = "mealy_fsm.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  (* src = "mealy_fsm.v:11.15-11.17" *)
  wire [2:0] st;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(st[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor4_1 _05_ (
    .A(_03_),
    .B(st[0]),
    .C(st[1]),
    .D(in),
    .Y(out)
  );
  sky130_fd_sc_hd__o21a_1 _06_ (
    .A1(st[0]),
    .A2(st[1]),
    .B1(st[2]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _07_ (
    .A(st[1]),
    .B(in),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a211oi_1 _08_ (
    .A1(st[0]),
    .A2(st[1]),
    .B1(_00_),
    .C1(_01_),
    .Y(n_st[0])
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(st[0]),
    .B(st[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a211oi_1 _10_ (
    .A1(_03_),
    .A2(_02_),
    .B1(_00_),
    .C1(in),
    .Y(n_st[1])
  );
  sky130_fd_sc_hd__and4_1 _11_ (
    .A(_03_),
    .B(st[0]),
    .C(st[1]),
    .D(in),
    .X(n_st[2])
  );
  (* src = "mealy_fsm.v:14.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(n_st[0]),
    .Q(st[0]),
    .RESET_B(rst_n)
  );
  (* src = "mealy_fsm.v:14.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(n_st[1]),
    .Q(st[1]),
    .RESET_B(rst_n)
  );
  (* src = "mealy_fsm.v:14.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(n_st[2]),
    .Q(st[2]),
    .RESET_B(rst_n)
  );
endmodule
