/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "4_1mux.v:1.1-17.10" *)
module mux4_1(a, b, c, d, sel, y);
  (* src = "4_1mux.v:4.22-4.23" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "4_1mux.v:4.24-4.25" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "4_1mux.v:4.26-4.27" *)
  input [3:0] c;
  wire [3:0] c;
  (* src = "4_1mux.v:4.28-4.29" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "4_1mux.v:5.16-5.19" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "4_1mux.v:6.27-6.28" *)
  output [3:0] y;
  wire [3:0] y;
  sky130_fd_sc_hd__mux4_2 _0_ (
    .A0(a[0]),
    .A1(b[0]),
    .A2(c[0]),
    .A3(d[0]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(y[0])
  );
  sky130_fd_sc_hd__mux4_2 _1_ (
    .A0(a[1]),
    .A1(b[1]),
    .A2(c[1]),
    .A3(d[1]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(y[1])
  );
  sky130_fd_sc_hd__mux4_2 _2_ (
    .A0(a[2]),
    .A1(b[2]),
    .A2(c[2]),
    .A3(d[2]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(y[2])
  );
  sky130_fd_sc_hd__mux4_2 _3_ (
    .A0(a[3]),
    .A1(b[3]),
    .A2(c[3]),
    .A3(d[3]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(y[3])
  );
endmodule
