/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "piso.v:1.1-22.10" *)
module piso(clk, rst, load, data, q);
  wire _0_;
  wire _1_;
  (* src = "piso.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "piso.v:5.18-5.22" *)
  input [3:0] data;
  wire [3:0] data;
  (* src = "piso.v:4.19-4.23" *)
  input load;
  wire load;
  (* src = "piso.v:8.16-8.19" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] mem;
  (* src = "piso.v:6.16-6.17" *)
  output q;
  wire q;
  (* src = "piso.v:4.15-4.18" *)
  input rst;
  wire rst;
  (* src = "piso.v:9.37-9.42" *)
  wire rst_n;
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(mem[0]),
    .A1(q),
    .S(load),
    .X(_0_)
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(mem[0]),
    .A1(data[0]),
    .S(load),
    .X(_1_)
  );
  (* src = "piso.v:9.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(rst_n)
  );
  (* src = "piso.v:9.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(_1_),
    .Q(mem[0]),
    .RESET_B(rst_n)
  );
endmodule
