/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "sr_ff_sync.v:1.1-20.10" *)
module sr_ff_sync(clk, rst_n, S, R, q);
  wire _0_;
  wire _1_;
  (* src = "sr_ff_sync.v:3.13-3.14" *)
  input R;
  wire R;
  (* src = "sr_ff_sync.v:3.11-3.12" *)
  input S;
  wire S;
  (* src = "sr_ff_sync.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "sr_ff_sync.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "sr_ff_sync.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__nor2_1 _2_ (
    .A(q),
    .B(S),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nor3b_1 _3_ (
    .A(R),
    .B(_1_),
    .C_N(rst_n),
    .Y(_0_)
  );
  (* src = "sr_ff_sync.v:6.5-19.8" *)
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
