/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "t_ff_sync.v:1.1-15.10" *)
module t_ff_sync(clk, rst_n, t, q);
  wire _0_;
  wire _1_;
  (* src = "t_ff_sync.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "t_ff_sync.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "t_ff_sync.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  (* src = "t_ff_sync.v:3.11-3.12" *)
  input t;
  wire t;
  sky130_fd_sc_hd__xor2_1 _2_ (
    .A(q),
    .B(t),
    .X(_1_)
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(rst_n),
    .B(_1_),
    .X(_0_)
  );
  (* src = "t_ff_sync.v:6.5-14.8" *)
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
