/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "2_1mux.v:1.1-10.10" *)
module mux2_1(a, b, sel, out);
  (* src = "2_1mux.v:4.22-4.23" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "2_1mux.v:4.24-4.25" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "2_1mux.v:6.23-6.26" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "2_1mux.v:5.12-5.15" *)
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(a[0]),
    .A1(b[0]),
    .S(sel),
    .X(out[0])
  );
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(a[1]),
    .A1(b[1]),
    .S(sel),
    .X(out[1])
  );
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(a[2]),
    .A1(b[2]),
    .S(sel),
    .X(out[2])
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(a[3]),
    .A1(b[3]),
    .S(sel),
    .X(out[3])
  );
endmodule
