/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "t_ff_async.v:1.1-15.10" *)
module t_ff_async(clk, rst_n, t, q);
  wire _0_;
  (* src = "t_ff_async.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "t_ff_async.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "t_ff_async.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  (* src = "t_ff_async.v:3.11-3.12" *)
  input t;
  wire t;
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(q),
    .B(t),
    .X(_0_)
  );
  (* src = "t_ff_async.v:6.5-14.8" *)
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(rst_n)
  );
endmodule
