/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "priority_encoder.v:1.1-20.10" *)
module p_encoder(d, o, valid);
  wire _0_;
  (* src = "priority_encoder.v:2.16-2.17" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "priority_encoder.v:3.21-3.22" *)
  output [1:0] o;
  wire [1:0] o;
  (* src = "priority_encoder.v:4.16-4.21" *)
  output valid;
  wire valid;
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(d[2]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _2_ (
    .A(d[2]),
    .SLEEP(d[3]),
    .X(o[1])
  );
  sky130_fd_sc_hd__or3_1 _3_ (
    .A(d[0]),
    .B(d[1]),
    .C(o[1]),
    .X(valid)
  );
  sky130_fd_sc_hd__a21o_1 _4_ (
    .A1(d[1]),
    .A2(_0_),
    .B1(d[3]),
    .X(o[0])
  );
endmodule
