/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "moore_fsm.v:1.1-54.10" *)
module moore(clk, rst_n, in, out);
  (* src = "moore_fsm.v:44.5-53.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "moore_fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "moore_fsm.v:2.21-2.23" *)
  input in;
  wire in;
  (* src = "moore_fsm.v:12.20-12.24" *)
  wire [2:0] n_st;
  (* src = "moore_fsm.v:3.16-3.19" *)
  output out;
  wire out;
  (* src = "moore_fsm.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  (* src = "moore_fsm.v:12.15-12.17" *)
  wire [2:0] st;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(st[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _05_ (
    .A(st[0]),
    .B(st[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4b_1 _06_ (
    .A(st[0]),
    .B(st[1]),
    .C(in),
    .D_N(st[2]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a41o_1 _07_ (
    .A1(_03_),
    .A2(st[0]),
    .A3(st[1]),
    .A4(in),
    .B1(_00_),
    .X(n_st[2])
  );
  sky130_fd_sc_hd__o21ai_0 _08_ (
    .A1(st[2]),
    .A2(st[0]),
    .B1(st[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o31a_1 _09_ (
    .A1(st[2]),
    .A2(st[1]),
    .A3(in),
    .B1(_02_),
    .X(n_st[0])
  );
  sky130_fd_sc_hd__nor3b_1 _10_ (
    .A(in),
    .B(_01_),
    .C_N(_02_),
    .Y(n_st[1])
  );
  (* src = "moore_fsm.v:44.5-53.8" *)
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(_00_),
    .Q(out),
    .RESET_B(rst_n)
  );
  (* src = "moore_fsm.v:15.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(n_st[0]),
    .Q(st[0]),
    .RESET_B(rst_n)
  );
  (* src = "moore_fsm.v:15.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(n_st[1]),
    .Q(st[1]),
    .RESET_B(rst_n)
  );
  (* src = "moore_fsm.v:15.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(n_st[2]),
    .Q(st[2]),
    .RESET_B(rst_n)
  );
endmodule
