/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "decoder2_4.v:1.1-6.10" *)
module decoder2_4(a, y);
  (* src = "decoder2_4.v:2.16-2.17" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "decoder2_4.v:3.17-3.18" *)
  output [3:0] y;
  wire [3:0] y;
  sky130_fd_sc_hd__nor2_1 _0_ (
    .A(a[0]),
    .B(a[1]),
    .Y(y[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1_ (
    .A(a[0]),
    .SLEEP(a[1]),
    .X(y[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _2_ (
    .A(a[1]),
    .SLEEP(a[0]),
    .X(y[2])
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(a[0]),
    .B(a[1]),
    .X(y[3])
  );
endmodule
