/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "pipo.v:1.1-16.10" *)
module pipo(clk, rst_n, data, q);
  (* src = "pipo.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "pipo.v:5.18-5.22" *)
  input [3:0] data;
  wire [3:0] data;
  (* src = "pipo.v:6.23-6.24" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "pipo.v:4.15-4.20" *)
  input rst_n;
  wire rst_n;
  (* src = "pipo.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(data[0]),
    .Q(q[0]),
    .RESET_B(rst_n)
  );
  (* src = "pipo.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(data[1]),
    .Q(q[1]),
    .RESET_B(rst_n)
  );
  (* src = "pipo.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(data[2]),
    .Q(q[2]),
    .RESET_B(rst_n)
  );
  (* src = "pipo.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(data[3]),
    .Q(q[3]),
    .RESET_B(rst_n)
  );
endmodule
