/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "jk_ff_async.v:1.1-20.10" *)
module jk_ff_async(clk, rst_n, J, K, q);
  wire _0_;
  wire _1_;
  (* src = "jk_ff_async.v:3.11-3.12" *)
  input J;
  wire J;
  (* src = "jk_ff_async.v:3.13-3.14" *)
  input K;
  wire K;
  (* src = "jk_ff_async.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "jk_ff_async.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "jk_ff_async.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__nor2_1 _2_ (
    .A(q),
    .B(J),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a21oi_1 _3_ (
    .A1(q),
    .A2(K),
    .B1(_1_),
    .Y(_0_)
  );
  (* src = "jk_ff_async.v:6.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(rst_n)
  );
endmodule
