/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "siso.v:1.1-17.10" *)
module siso(clk, rst_n, data, load, q);
  (* src = "siso.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "siso.v:4.21-4.25" *)
  input data;
  wire data;
  (* src = "siso.v:4.26-4.30" *)
  input load;
  wire load;
  (* src = "siso.v:5.12-5.13" *)
  output q;
  wire q;
  (* src = "siso.v:4.15-4.20" *)
  input rst_n;
  wire rst_n;
  (* src = "siso.v:7.16-7.25" *)
  wire [3:0] shift_reg;
  (* src = "siso.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(shift_reg[1]),
    .Q(q),
    .RESET_B(rst_n)
  );
  (* src = "siso.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(shift_reg[2]),
    .Q(shift_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "siso.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(shift_reg[3]),
    .Q(shift_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "siso.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(data),
    .Q(shift_reg[3]),
    .RESET_B(rst_n)
  );
  assign shift_reg[0] = q;
endmodule
