/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "mux8_1.v:1.1-9.10" *)
module mux8_1(d, sel, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "mux8_1.v:4.24-4.25" *)
  input [31:0] d;
  wire [31:0] d;
  (* src = "mux8_1.v:6.23-6.26" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "mux8_1.v:5.16-5.19" *)
  input [2:0] sel;
  wire [2:0] sel;
  sky130_fd_sc_hd__mux4_2 _08_ (
    .A0(d[16]),
    .A1(d[20]),
    .A2(d[24]),
    .A3(d[28]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux4_2 _09_ (
    .A0(d[0]),
    .A1(d[4]),
    .A2(d[8]),
    .A3(d[12]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(_01_),
    .A1(_00_),
    .S(sel[2]),
    .X(out[0])
  );
  sky130_fd_sc_hd__mux4_2 _11_ (
    .A0(d[17]),
    .A1(d[21]),
    .A2(d[25]),
    .A3(d[29]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux4_2 _12_ (
    .A0(d[1]),
    .A1(d[5]),
    .A2(d[9]),
    .A3(d[13]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(_03_),
    .A1(_02_),
    .S(sel[2]),
    .X(out[1])
  );
  sky130_fd_sc_hd__mux4_2 _14_ (
    .A0(d[18]),
    .A1(d[22]),
    .A2(d[26]),
    .A3(d[30]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux4_2 _15_ (
    .A0(d[2]),
    .A1(d[6]),
    .A2(d[10]),
    .A3(d[14]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(_05_),
    .A1(_04_),
    .S(sel[2]),
    .X(out[2])
  );
  sky130_fd_sc_hd__mux4_2 _17_ (
    .A0(d[19]),
    .A1(d[23]),
    .A2(d[27]),
    .A3(d[31]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux4_2 _18_ (
    .A0(d[3]),
    .A1(d[7]),
    .A2(d[11]),
    .A3(d[15]),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(_07_),
    .A1(_06_),
    .S(sel[2]),
    .X(out[3])
  );
endmodule
