/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "d_ff_sync.v:1.1-14.10" *)
module d_ff_sync(clk, rst_n, d, q);
  wire _0_;
  (* src = "d_ff_sync.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "d_ff_sync.v:3.11-3.12" *)
  input d;
  wire d;
  (* src = "d_ff_sync.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "d_ff_sync.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(d),
    .B(rst_n),
    .X(_0_)
  );
  (* src = "d_ff_sync.v:6.5-13.8" *)
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
