/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "sync_counter.v:1.1-17.10" *)
module counter(clk, rst_n, counter);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "sync_counter.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "sync_counter.v:6.27-6.34" *)
  output [3:0] counter;
  wire [3:0] counter;
  (* src = "sync_counter.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _08_ (
    .A(rst_n),
    .SLEEP(counter[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__o21ai_0 _09_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(rst_n),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _10_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand3_1 _11_ (
    .A(counter[0]),
    .B(counter[2]),
    .C(counter[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(counter[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3b_1 _13_ (
    .A_N(_06_),
    .B(rst_n),
    .C(_05_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _14_ (
    .A(counter[3]),
    .B(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and2_0 _15_ (
    .A(rst_n),
    .B(_07_),
    .X(_03_)
  );
  (* src = "sync_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(counter[0])
  );
  (* src = "sync_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(counter[1])
  );
  (* src = "sync_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(counter[2])
  );
  (* src = "sync_counter.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(counter[3])
  );
endmodule
