/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "jk_ff_sync.v:1.1-20.10" *)
module jk_ff_sync(clk, rst_n, J, K, q);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "jk_ff_sync.v:3.11-3.12" *)
  input J;
  wire J;
  (* src = "jk_ff_sync.v:3.13-3.14" *)
  input K;
  wire K;
  (* src = "jk_ff_sync.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "jk_ff_sync.v:4.16-4.17" *)
  output q;
  wire q;
  (* src = "jk_ff_sync.v:2.15-2.20" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__nand2b_1 _3_ (
    .A_N(K),
    .B(q),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nand2b_1 _4_ (
    .A_N(q),
    .B(J),
    .Y(_2_)
  );
  sky130_fd_sc_hd__a21boi_0 _5_ (
    .A1(_1_),
    .A2(_2_),
    .B1_N(rst_n),
    .Y(_0_)
  );
  (* src = "jk_ff_sync.v:6.5-19.8" *)
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
