/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "modulo_N_counter.v:1.1-18.10" *)
module modulo(clk, rst_n, counter);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "modulo_N_counter.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "modulo_N_counter.v:5.32-5.39" *)
  output [3:0] counter;
  wire [3:0] counter;
  (* src = "modulo_N_counter.v:4.15-4.20" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__nand4bb_1 _10_ (
    .A_N(counter[1]),
    .B_N(counter[2]),
    .C(counter[0]),
    .D(counter[3]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(rst_n),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _12_ (
    .A(counter[0]),
    .B(_05_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _14_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a21oi_1 _15_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .B1(counter[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3_1 _16_ (
    .A(counter[1]),
    .B(counter[2]),
    .C(counter[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor3_1 _17_ (
    .A(_05_),
    .B(_07_),
    .C(_08_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(counter[3]),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _19_ (
    .A(_05_),
    .B(_09_),
    .Y(_03_)
  );
  (* src = "modulo_N_counter.v:7.5-17.8" *)
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_),
    .Q(counter[0])
  );
  (* src = "modulo_N_counter.v:7.5-17.8" *)
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_01_),
    .Q(counter[1])
  );
  (* src = "modulo_N_counter.v:7.5-17.8" *)
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(counter[2])
  );
  (* src = "modulo_N_counter.v:7.5-17.8" *)
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_03_),
    .Q(counter[3])
  );
endmodule
